spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./loan_applications_db
    username: user
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
