spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./loan_applications_db
    username: user
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuit breaker:
    instances:
      fallBack:
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 1
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED